name: Release
on:
  push:
    tags:
    - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  build-windows-release:
    name: build-release
    needs: [tagged-release]
    runs-on: windows-latest

    env:
      TARGET_DIR: ./target
      RUST_BACKTRACE: 1
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --examples --verbose

    - name: Build archive
      shell: bash
      run: |
        staging="examples-windows"
        mkdir -p "$staging"

        cp "target/release/examples/read_snapshot.exe" "$staging/"

        7z a "$staging.zip" "$staging"

    - name: Upload release archive
      uses: softprops/action-gh-release@v1
      with:
        files: |
          examples-windows.zip
  